---
title: Data-synth flow
---
flowchart TD
    A(EHR) --> B[conversation_init]
    B --"Generate first patient question"--> C[doctor]
subgraph "Core loop"
    C
    D
end
    C --> D[patient]
    C --> E[Drug info]
    C --> F[Regulator]
    C --> G[Information retriver]
    D --> C